require 'bson'
require 'moped'
require 'mongoid'
require 'mongoid/railtie'
require 'mongoid/tree'
# require 'mongoid_migration'
require 'mongo_session_store'
require 'devise'
require 'devise/orm/mongoid'
require 'devise-encryptable'
require 'kaminari'
require 'haml'
require 'liquid'
require 'solid'
require 'bootstrap-sass-rails'
require 'formtastic'
require 'formtastic-bootstrap'
require 'font-awesome-sass'
require 'responders'
require 'carrierwave'
require 'custom_fields'
require 'mimetype_fu'
require 'actionmailer_with_request'
require 'httparty'
require 'redcloth'
require 'redcarpet'
require 'dragonfly'
require 'pundit'
require 'cells'
require 'sanitize'
require 'stringex'
require 'csv'

require 'compass-rails'
require 'codemirror/rails'
require 'jquery/rails'
require 'backbone-rails'
# require 'tinymce/rails'
# require 'aloha/rails'
