source :rubygems

gem 'sqlite3',                  '~> 0.1.1'
gem 'locomotive_cms',           :path => '../../'

group :development do
  # Using unicorn_rails instead of webrick (default server)
  gem 'unicorn',                '~> 3.3.1'
end

group :test, :development do
  gem 'ruby-debug',             :platforms => :mri_18
  gem 'ruby-debug19',           :platforms => :mri_19
end

group :test do
  gem 'autotest',               '~> 4.4.6'
  gem 'ZenTest',                '~> 4.4.2'
  gem 'growl-glue',             '~> 1.0.7'
  gem 'rspec-rails',            '~> 2.3.1'
  gem 'factory_girl_rails',     '~> 1.0.1'
  gem 'pickle',                 '~> 0.4.4'
  gem 'capybara',               '~> 0.4.0'
  gem 'database_cleaner',       '~> 0.6.0'
  gem 'cucumber',               '~> 0.8.5'
  gem 'cucumber-rails',         '~> 0.3.2'
  gem 'spork',                  '~> 0.8.4'
  gem 'launchy',                '~> 0.3.7'
  gem 'mocha',                  :git => 'git://github.com/floehopper/mocha.git'
  gem 'mongoid-rspec',          '~> 1.3.2'
end